databases:
  # A PostgreSQL database defined in its own block
  - name: mindspace-db
    plan: free

services:
  # A Redis instance for the channel layer
  - type: redis
    name: redis-cache
    plan: free
    ipAllowList: [] # <-- ADD THIS BLOCK. An empty list allows all internal traffic.

  # The Daphne web service
  - type: web
    name: mindspace
    plan: free
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "daphne mindspace.asgi:application -p $PORT -b 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mindspace-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.2