services:
  # A PostgreSQL database
  - type: postgres # <-- CORRECTED from psql
    name: postgres-db # Changed name to avoid conflict with type
    plan: free

  # A Redis instance for the channel layer
  - type: redis
    name: redis-cache # Changed name to avoid conflict with type
    plan: free

  # The Daphne web service
  - type: web
    name: mindspace
    plan: free
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "daphne mindspace.asgi:application -p $PORT -b 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.2