# Generated by Django 5.2.5 on 2025-09-07 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='user',
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='pseudonym',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumpost',
            name='pseudonym',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
