# Generated by Django 5.2.5 on 2025-09-07 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0002_remove_forumcomment_user_remove_forumpost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='anon_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumpost',
            name='anon_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
